name: lint-test
on: 
  push:
    # branches-ignore:
    #   - "main"
    #   - "develop"
jobs:
  py-lint:
    runs-on: ubuntu-latest
    container: 
      image: python:3.10-buster
      volumes:
        - /tmp/app:/app
    steps:
    - name: code-checkout
      uses: actions/checkout@v3
    - name: runing-pylint
      run:  | 
       cd /app && ls -lthr 
      #continue-on-error: true