name: lint-test
on: 
  push:
    # branches-ignore:
    #   - "main"
    #   - "develop"
jobs:
  py-lint:
    runs-on: ubuntu-latest
    container: 
      image: python:3.10-buster
    steps:
    - name: code-checkout
      uses: actions/checkout@v3
    - name: runing-pylint
      run:  | 
       cd docker-app/app && ls -lthr && pip install -r requirements.txt
      continue-on-error: true
  build-test:
    needs: py-lint
    runs-on: ubuntu-latest
    steps:
    - name: code-checkout
      uses: actions/checkout@v3
    - name: build-docker
      run: | 
       tag=$(echo $${GITHUB_SHA} | cut -c1-5) && export tag
       echo $tag
       cd docker-app && docker build -t py:$tag .